dataset:
  batch_size: 64
  dev:
    path: data/UIT-ViSFD/dev.json
    type: UIT_ViSFD_Dataset_ABSA
  num_workers: 6
  test:
    path: data/UIT-ViSFD/test.json
    type: UIT_ViSFD_Dataset_ABSA
  train:
    path: data/UIT-ViSFD/train.json
    type: UIT_ViSFD_Dataset_ABSA
model:
  architecture: RNNmodel_ABSA
  bidirectional: 2
  d_model: 256
  device: cuda
  dropout: 0.2
  input_dim: 256
  label_smoothing: 0.1
  model_type: LSTM
  name: BiLSTM_Model6layer_UIT_ViSFD_bpe_ABSA
  num_categories: 11
  num_layer: 6
  num_output: 5
task: AspectBasedClassification
training:
  checkpoint_path: checkpoints/UIT_ViSFD/ABSA/s2/BiLSTM/bpe
  learning_rate: 0.1
  patience: 50
  score: f1
  seed: 42
  warmup: 500
vocab:
  aspect: aspect
  aspect_label: sentiment
  bos_id: 1
  bos_piece: <s>
  eos_id: 2
  eos_piece: </s>
  label: label
  min_freq: 5
  model_prefix: checkpoints/UIT_ViSFD/ABSA/s2/BiLSTM/bpe/UIT_ViSFD_bpe
  model_type: bpe
  pad_id: 0
  pad_piece: <pad>
  path:
    dev: data/UIT-ViSFD/dev.json
    test: data/UIT-ViSFD/test.json
    train: data/UIT-ViSFD/train.json
  schema: 2
  space_id: 4
  space_token: <space>
  task_type: aspect_based
  text: comment
  type: BPETokenizer
  unk_id: 3
  unk_piece: <unk>
  vocab_size: 442
